### ISSUE TITLE
 Please consider contributing some of this to our website. #1 

### ISSUE THREAD

**Issue by nickmackenzie** [whiteside-daniel/zoho-deluge-scripts#1]
Hello,

I am a fellow deluge user and am creating sort of a 'go-to' docs for deluge/zoho tricks. Please consider contributing to the site!

https://github.com/nickmackenzie/dont-get-zohod

https://dont-get-zohod.vercel.app/

To contribute, its just .md files added to the pages directory. Fairly straighforward and would help grow the community.

Thanks

**Comment by whiteside-daniel** [comment]
Howdy Nick,
The GitHub link seems to be broken, I'm getting a 404 error. Is the "Don't Get Zohod" repo still live?

I'd be happy to share a few scripts to your library.

Daniel W

**Comment by nickmackenzie** [comment]
Hey Daniel,

My bad! The repo was private still. Your good now :) and thanks!
